pong_v1 pettingzoo
<SubprocVectorEnv instance>
Agents No. [1] (index starting from 0) are not learnable.
Arguments:  {'env_name': 'pong_v1', 'env_type': 'pettingzoo', 'num_envs': 5, 'ram': True, 'seed': 12234, 'algorithm': 'DQN', 'algorithm_spec': {'episodic_update': False, 'dueling': True, 'replay_buffer_size': '1e5', 'gamma': 0.99, 'multi_step': 1, 'target_update_interval': 1000, 'eps_start': 1.0, 'eps_final': 0.01, 'eps_decay': 30000}, 'hidden_dim': 64, 'batch_size': 64, 'max_episodes': 10000, 'max_steps_per_episode': 10000, 'train_start_frame': 10000, 'optimizer': 'adam', 'learning_rate': '1e-4', 'device': 'gpu', 'update_itr': 1, 'log_avg_window': 20, 'log_interval': 20, 'render': False, 'test': False, 'exploit': False, 'load_model_idx': False, 'load_model_full_path': False, 'net_architecture': {'hidden_dim_list': [64, 64, 64], 'hidden_activation': 'Tanh', 'output_activation': False}, 'marl_method': 'selfplay', 'marl_spec': {'selfplay_score_delta': 20, 'trainable_agent_idx': 0, 'opponent_idx': 1}}
Traceback (most recent call last):
  File "run.py", line 27, in <module>
    rollout(env, model, args)
  File "/home/zihan/research/MARS/mars_core/rollout.py", line 17, in rollout
    rollout_normal(env, model, args)
  File "/home/zihan/research/MARS/mars_core/rollout.py", line 47, in rollout_normal
    obs_, reward, done, info = env.step(action)  # requires action: (envs, agents, dim)
  File "/home/zihan/research/MARS/mars_core/env/wrappers/vecenv_wrappers.py", line 340, in step
    assert len(action) == len(id)
AssertionError
