pygame 2.0.0 (SDL 2.0.12, python 3.7.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "general_exploit.py", line 64, in <module>
    launch_rollout(parser_args.env, parser_args.method, parser_args.load_id, parser_args.save_id)
  File "general_exploit.py", line 40, in launch_rollout
    file_path = get_latest_file_in_folder(folder, id=0)  # load from the first agent model of the two
  File "general_exploit.py", line 20, in get_latest_file_in_folder
    last_idx = idx_list[-1]
IndexError: list index out of range
